/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Hbase_CONSTANTS_H
#define Hbase_CONSTANTS_H

#include "Hbase_types.h"

namespace apache { namespace hadoop { namespace hbase { namespace thrift {

class HbaseConstants {
 public:
  HbaseConstants();

};

extern const HbaseConstants g_Hbase_constants;

}}}} // namespace

#endif
